main:
  ROS_node_name: Python_Node
  headless_mode: false
  log_time: false
  logging_level: NOTSET
  max_run_time: 50000
  numpy_print_precision: 2
  pose_source: tf
  use_ROS: true
robots:
  Deckard:
    goal_planner_cfg:
      type_: audio
    pose_source: tf
    type_: cop
    use: true
  Pris:
    goal_planner_cfg:
      type_: stationary
    pose_source: tf
    type_: cop
    use: false
  Roy:
    goal_planner_cfg:
      type_: pomdp
    pose_source: tf
    type_: robber
    use: false
  Zhora:
    goal_planner_cfg:
      type_: stationary
    pose_source: tf
    type_: cop
    use: false
